name: CI
on:
  push:
    branches:
      - main
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          always-auth: true
          registry-url: https://registry.npmjs.org

      - name: Get cached dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        id: install
        run: npm install

      - name: Lint
        id: lint
        run: npm run lint

      - name: Run tests
        id: tests
        run: npm test

      - name: Submit coverage
        id: codecov
        uses: codecov/codecov-action@v2
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./coverage/coverage-final.json

      - name: Release version
        id: release
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
